management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: "full"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "*"
#        include: "health,info"
#        exclude: "env,beans"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug